{
	"version": 1571529265,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/fundo.png",
		"images/laranja-sheet0.png",
		"images/laranja-sheet1.png",
		"images/cesto-sheet0.png",
		"images/cesto-sheet1.png",
		"images/laranja2-sheet0.png",
		"images/laranja2-sheet1.png",
		"images/laranja4-sheet0.png",
		"images/unidade1-sheet0.png",
		"images/unidade2-sheet0.png",
		"images/unidade3-sheet0.png",
		"images/unidade4-sheet0.png",
		"images/unidade5-sheet0.png",
		"images/unidade6-sheet0.png",
		"images/unidade7-sheet0.png",
		"images/unidade8-sheet0.png",
		"images/unidade9-sheet0.png",
		"images/penssamento-sheet0.png",
		"images/penssamento-sheet1.png",
		"images/falapersonagem-sheet0.png",
		"images/vezespenssamento-sheet0.png",
		"images/personagem2-sheet0.png",
		"images/personagem2-sheet1.png",
		"images/sol-sheet0.png",
		"images/sol-sheet1.png",
		"images/cursorinterrogação-sheet0.png",
		"images/mãocomfruta-sheet0.png",
		"images/soma-sheet0.png",
		"images/soma-sheet1.png",
		"images/subtração-sheet0.png",
		"images/subtração-sheet1.png",
		"images/multiplicação-sheet0.png",
		"images/multiplicação-sheet1.png",
		"images/divisão-sheet0.png",
		"images/divisão-sheet1.png",
		"images/tiledbackground.png",
		"images/morango-sheet0.png",
		"images/morango-sheet1.png",
		"images/estrela-sheet0.png",
		"images/estrela-sheet1.png",
		"images/fundoresposta-sheet0.png",
		"images/igual-sheet0.png",
		"images/operadormenos-sheet0.png",
		"images/operadormenos2-sheet0.png",
		"images/interrogação-sheet0.png",
		"images/interrogação-sheet1.png",
		"images/fundosub.png",
		"images/falapersonagemsub-sheet0.png",
		"images/mãojoia-sheet0.png",
		"images/seta-sheet0.png",
		"images/fundosubtracao.png",
		"images/solo-sheet0.png",
		"images/acaopersonagem-sheet0.png",
		"images/jogador-sheet0.png",
		"images/soloflutuante-sheet0.png",
		"images/falapersonagemdiv-sheet0.png",
		"images/janelafunfomenu-sheet0.png",
		"images/janelafrentemenu-sheet0.png",
		"images/bolo-sheet0.png",
		"images/bolo-sheet1.png",
		"images/bolo-sheet2.png",
		"images/operadorsomaanimacao-sheet0.png",
		"images/operadorsubtracaoanimacao-sheet0.png",
		"images/operadormultiplicacaoanimacao-sheet0.png",
		"images/operadordivisaoanimacao-sheet0.png",
		"images/persoamarelo-sheet0.png",
		"images/persoamarelo-sheet1.png",
		"images/persoamarelo-sheet2.png",
		"images/porta-sheet0.png",
		"images/fundosomafase2.png",
		"images/corverde-sheet0.png",
		"images/corazul-sheet0.png",
		"images/corvermelha-sheet0.png",
		"images/coramarela-sheet0.png",
		"images/cursorcolorido-sheet0.png",
		"images/balaocolorido0-sheet0.png",
		"images/balaocolorido0-sheet1.png",
		"images/balaocolorido0-sheet2.png",
		"media/cancel - 1.m4a",
		"media/cancel - 1.ogg",
		"media/ok - 1.m4a",
		"media/ok - 1.ogg",
		"media/oops1.m4a",
		"media/oops1.ogg",
		"media/oooscary1.m4a",
		"media/oooscary1.ogg",
		"media/bump1.m4a",
		"media/bump1.ogg",
		"media/mattoglseby - 5.m4a",
		"media/mattoglseby - 5.ogg",
		"media/mattoglseby - 7.m4a",
		"media/mattoglseby - 7.ogg",
		"media/mattoglseby - 8.m4a",
		"media/mattoglseby - 8.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"loading-logo.png",
		"icon-256.png"
	]
}